INSERT INTO product_images (id, product_id, url, alt, sort_order, is_primary) VALUES
('img-aod-box', 'prod-aod', 'https://r2.ridethetide.site/products/aod-9604-box.png', 'AOD-9604 box', 2, 0),
('img-bpc157-box', 'prod-bpc157', 'https://r2.ridethetide.site/products/bpc-157-box.png', 'BPC-157 box', 2, 0),
('img-bpctb-box', 'prod-bpctb', 'https://r2.ridethetide.site/products/bpc-157-tb-500-box.png', 'BPC-157 + TB-500 box', 2, 0),
('img-cag-box', 'prod-cag', 'https://r2.ridethetide.site/products/cagrilintide-box.png', 'Cagrilintide box', 2, 0),
('img-cjcipa-box', 'prod-cjcipa', 'https://r2.ridethetide.site/products/cjc-1295-ipamorelin-box.png', 'CJC-1295 + Ipamorelin box', 2, 0),
('img-cjcnd-box', 'prod-cjcnd', 'https://r2.ridethetide.site/products/cjc-1295-no-dac-box.png', 'CJC-1295 No DAC box', 2, 0),
('img-dp1s-box', 'prod-dp1s', 'https://r2.ridethetide.site/products/dp1-s-box.png', 'DP1-S box', 2, 0),
('img-dp2t-box', 'prod-dp2t', 'https://r2.ridethetide.site/products/dp2-t-box.png', 'DP2-T box', 2, 0),
('img-dp3r-box', 'prod-dp3r', 'https://r2.ridethetide.site/products/dp3-r-box.png', 'DP3-R box', 2, 0),
('img-dsip-box', 'prod-dsip', 'https://r2.ridethetide.site/products/dsip-box.png', 'DSIP box', 2, 0),
('img-ghk-box', 'prod-ghk', 'https://r2.ridethetide.site/products/ghk-cu-box.png', 'GHK-Cu box', 2, 0),
('img-glow-box', 'prod-glow', 'https://r2.ridethetide.site/products/glow-box.png', 'Glow box', 2, 0),
('img-hex-box', 'prod-hex', 'https://r2.ridethetide.site/products/hexarelin-box.png', 'Hexarelin box', 2, 0),
('img-igf-box', 'prod-igf', 'https://r2.ridethetide.site/products/igf-1-lr3-box.png', 'IGF-1 LR3 box', 2, 0),
('img-ipa-box', 'prod-ipa', 'https://r2.ridethetide.site/products/ipamorelin-box.png', 'Ipamorelin box', 2, 0),
('img-kiss-box', 'prod-kiss', 'https://r2.ridethetide.site/products/kisspeptin-box.png', 'Kisspeptin box', 2, 0),
('img-klow-box', 'prod-klow', 'https://r2.ridethetide.site/products/klow-box.png', 'Klow box', 2, 0),
('img-kpv-box', 'prod-kpv', 'https://r2.ridethetide.site/products/kpv-box.png', 'KPV box', 2, 0),
('img-glu-box', 'prod-glu', 'https://r2.ridethetide.site/products/l-glutathione-box.png', 'L-Glutathione box', 2, 0),
('img-mt2-box', 'prod-mt2', 'https://r2.ridethetide.site/products/melanotan-ii-box.png', 'Melanotan II box', 2, 0),
('img-mots-box', 'prod-mots', 'https://r2.ridethetide.site/products/mots-c-box.png', 'MOTS-C box', 2, 0),
('img-nad-box', 'prod-nad', 'https://r2.ridethetide.site/products/nad-plus-box.png', 'NAD+ box', 2, 0),
('img-oxy-box', 'prod-oxy', 'https://r2.ridethetide.site/products/oxytocin-box.png', 'Oxytocin box', 2, 0),
('img-pt141-box', 'prod-pt141', 'https://r2.ridethetide.site/products/pt-141-box.png', 'PT-141 box', 2, 0),
('img-sel-box', 'prod-sel', 'https://r2.ridethetide.site/products/selank-box.png', 'Selank box', 2, 0),
('img-sem-box', 'prod-sem', 'https://r2.ridethetide.site/products/semax-box.png', 'Semax box', 2, 0),
('img-serm-box', 'prod-serm', 'https://r2.ridethetide.site/products/sermorelin-box.png', 'Sermorelin box', 2, 0),
('img-tb500-box', 'prod-tb500', 'https://r2.ridethetide.site/products/tb-500-box.png', 'TB-500 box', 2, 0),
('img-tesa-box', 'prod-tesa', 'https://r2.ridethetide.site/products/tesamorelin-box.png', 'Tesamorelin box', 2, 0),
('img-ta1-box', 'prod-ta1', 'https://r2.ridethetide.site/products/thymosin-alpha-1-box.png', 'Thymosin Alpha-1 box', 2, 0);
